-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 01:29:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbPI3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbPI3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbPI3` DEFAULT CHARACTER SET utf8 ;
USE `dbPI3` ;

-- -----------------------------------------------------
-- Table `dbPI3`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPI3`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nomeCurso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcurso`),
  UNIQUE INDEX `idcurso_UNIQUE` (`idcurso` ASC, `nomeCurso` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPI3`.`coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPI3`.`coordenador` (
  `idcoordenador` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `matricula` INT UNSIGNED NOT NULL,
  `nomeCoordenador` VARCHAR(45) NOT NULL,
  `curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`idcoordenador`, `curso_idcurso`),
  INDEX `fk_coordenador_curso_idx` (`curso_idcurso` ASC),
  CONSTRAINT `fk_coordenador_curso`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `dbPI3`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPI3`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPI3`.`documento` (
  `iddocumento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `situacaoDoc` TINYINT NULL DEFAULT 0,
  `tipoDoc` VARCHAR(45) NOT NULL,
  `avaliacaoDoc` VARCHAR(45) NULL,
  `coordenador_idcoordenador` INT UNSIGNED NOT NULL,
  `coordenador_curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`iddocumento`, `coordenador_idcoordenador`, `coordenador_curso_idcurso`),
  INDEX `fk_documento_coordenador1_idx` (`coordenador_idcoordenador` ASC, `coordenador_curso_idcurso` ASC),
  CONSTRAINT `fk_documento_coordenador1`
    FOREIGN KEY (`coordenador_idcoordenador` , `coordenador_curso_idcurso`)
    REFERENCES `dbPI3`.`coordenador` (`idcoordenador` , `curso_idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPI3`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPI3`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nomeFunc` VARCHAR(45) NOT NULL,
  `matricula` INT NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dbPI3`.`curso`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbPI3`;
INSERT INTO `dbPI3`.`curso` (`idcurso`, `nomeCurso`) VALUES (1, 'Analise e desenvolvimento de sistemas');
INSERT INTO `dbPI3`.`curso` (`idcurso`, `nomeCurso`) VALUES (2, 'Psicologia');
INSERT INTO `dbPI3`.`curso` (`idcurso`, `nomeCurso`) VALUES (3, 'Moda');
INSERT INTO `dbPI3`.`curso` (`idcurso`, `nomeCurso`) VALUES (4, 'Engenharia Civil');
INSERT INTO `dbPI3`.`curso` (`idcurso`, `nomeCurso`) VALUES (5, 'Direito');

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbPI3`.`coordenador`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbPI3`;
INSERT INTO `dbPI3`.`coordenador` (`idcoordenador`, `matricula`, `nomeCoordenador`, `curso_idcurso`) VALUES (1, 111, 'João da Silva', 1);
INSERT INTO `dbPI3`.`coordenador` (`idcoordenador`, `matricula`, `nomeCoordenador`, `curso_idcurso`) VALUES (2, 222, 'Rebeca Borges', 2);
INSERT INTO `dbPI3`.`coordenador` (`idcoordenador`, `matricula`, `nomeCoordenador`, `curso_idcurso`) VALUES (3, 333, 'Pedro Santos', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbPI3`.`funcionario`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbPI3`;
INSERT INTO `dbPI3`.`funcionario` (`idfuncionario`, `nomeFunc`, `matricula`) VALUES (1, 'Rosa Maria', 1010);
INSERT INTO `dbPI3`.`funcionario` (`idfuncionario`, `nomeFunc`, `matricula`) VALUES (2, 'Cleber Machado', 1111);

COMMIT;

